title         : Nikola Balić     # Add your name
role          : Head of Growth        # Add your role/position
company       : Daytona               # Add your company name


description   : >-        # this means to ignore newlines until "baseurl:"
  Experienced growth strategist and innovation enthusiast, helping startups thrive and businesses embrace digital transformation. Let's boost development velocity together!
baseurl       : ""        # the subpath of your site, e.g. /blog
url           : "https://nkkko.github.io"       # the base hostname & protocol for your site, e.g. http://example.com
keywords      : niko, nkko, nkkko, growth
theme-color   : "#BB2649"       # Used for browser theme-color meta tag

gravatar      : b5219d812363aace4a38e34e14b8fdbe     # Gravatar md5 hash
image         : /assets/avatar.png                   # Add your avatar image src here
branding      : false                                 # Your name will be replaced with your logo if set to true, change your logo here "_includes/svg/logo.svg"


### Author Info ###
author:
  name              : Nikola Balić
  twitter           : nibalic
  github            : nkkko
  linkedin          : nikolabalic
  hackernoon        : nkko
  hackernews        : nkko
  researchgate      : Nikola_Balic
  orcid             : 0000-0002-4405-1470
#  goodreads         : nibalic
#  buy me a coffee   : nibalic
#  youtube           : nibalic
#  facebook          : nibalic
#  twitch            : nibalic
#  instagram         : nibalic
#  gitlab            : nibalic
#  codepen           : nibalic


### Analytics ###
analytics:
  enabled: true
  google:
    tracking_id: G-HFS5EDXYGW       #Add your Google analytics tracking ID here

sass:
    style: compressed

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - vendor